### ISSUE TITLE
UX

### ISSUE THREAD

**Issue by vbiaggig** [vbiaggi10/lim-2018-05-bc-core-pm-datadashboard#5]
Valeria
- [x] Investigar figma, marvel, invision

- [x] Entrevistar al usuario y tomar conclusiones

- [x] Diseñar el sketch vista 1 y 2

- [x] Diseñar Mockup vista 2

- [x] Actualizar el readme en funcion a este issue

Doda
- [x] Investigar figma, marvel, invision

- [x] Crear preguntas para entrevistar al usuario

- [x] Entrevistar al usuario y tomar conclusiones

- [x] Diseñar Mockup vista 1

- [x] Actualizar el readme en funcion a este issue

**Comment by DodaMaticorena** [comment]
Completed.
